apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: microservice-app
spec:
  template:
    spec: 
      containers:
        - image: docker.io/brycc12/microservice-app
          ports:
            - containerPort: 8080
          env:
            - name: NAME
              value: "Brayan Caicedo"
            - name: SERVICE
              value: "Knative V1"